name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        pod repo update
        pod install      
    - name: CocoaPods Action
      uses: ty0x2333/cocoapods-action@0.2.0
      with:
        # .xcworkspace file
        workspace: TeamBoostFire.xcworkspace
        # Shared scheme
        scheme: TeamBoostFireTests
