name: Swift

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild -workspace TeamBoostFire.xcworkspace -scheme TeamBoostFire build -allowProvisioningUpdates
#    - name: Run tests
#      run: swift test -v
